services:
  web_cache:
    image: redis:alpine
    restart: always
    networks:
      aiijc_development:

  web_production:
    build:
      context: web
    networks:
      aiijc_development:
        ipv4_address: 10.6.1.10
    environment:
      FLASK_MODEL_HOST: "http://model_production:8000"
      FLASK_REDIS_CONNECTION_URL: "redis://web_cache:6379/0"

    # Fixes high memory usage by uwsgi (about 8 GB)
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 5000:80


  model_production:
    build:
      context: model
    networks:
      aiijc_development:
        ipv4_address: 10.6.1.11
    volumes:
      - ./model/weights:/weights
    environment:
      WEIGHTS_PATH: /weights

networks:
  aiijc_development:
    driver: bridge
    ipam:
      config:
        - subnet: 10.6.1.0/24
